name: isar_reproduce
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

isar_version: &isar_version 3.0.2

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.1.1
  isar: *isar_version
  isar_flutter_libs: *isar_version

dev_dependencies:
  flutter_test:
    sdk: flutter

  isar_generator: *isar_version
  build_runner: any
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
